name: Mysql actions demo
run-name: ${{ github.actor }} is testing out Mysql GitHub Actions 🚀

on: [push]

jobs:
  setup_mysql_database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flyway_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL client and unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client unzip wget

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -proot --silent; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ Waiting... ($i)"
            sleep 2
          done

      - name: Deploy schema to MySQL
        run: |
          mysql -h 127.0.0.1 -u root -proot flyway_test < schema_changes.sql

      - name: Download Flyway CLI
        run: |
          wget -q https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz
          tar -xzf flyway-commandline-9.22.3-linux-x64.tar.gz
          sudo ln -s $PWD/flyway-9.22.3/flyway /usr/local/bin/flyway

      - name: Run migrations
       run: |
    docker run --rm -v "${{ github.workspace }}/migrations:/flyway/sql" redgate/flyway \
      -url=jdbc:mysql://mysql:3306/flyway_test -user=root -password=root \
      -locations=filesystem:/flyway/sql,filesystem:/flyway/sql/init,filesystem:/flyway/sql/update migrate

